version: '3'
services:
  app:
    build: .
    container_name: app
    labels:
      traefik.enable: "true"
    working_dir: /usr/src
    volumes: 
      - ./src:/usr/src/src
    tty: true
    ports:
      - "2000:2000"
    links:
      - mongo
  mongo:
    image: mongo:4.0
    tty: false
    ports:
      - "27017:27017"